#!/bin/env node
//  OpenShift sample Node application
var express = require('express');
var fs      = require('fs');
var bitcoinjs = require('bitcoinjs-lib');
var mongojs = require('mongojs');
var path = require('path');
//require('./models/wagers.js');

var wagers = [
    {
        id: 1,
        email:'J@J.com',
        amount:'3'
    },
    {
        id: 2,
        email:'ax@fable.com',
        amount:'0.21'
    }
];

/**
 *  Define the sample application.
 */
var SampleApp = function() {

    //  Scope.
    var self = this;
    var router = express.Router();
    var connection_string;
    var db;
    //var wagers = db.collection('wagers');
    

    /*  ================================================================  */
    /*  Helper functions.                                                 */
    /*  ================================================================  */

    /**
     *  Set up server IP address and port # using env variables/defaults.
     */
    self.setupVariables = function() {
        //  Set the environment variables we need.
        self.ipaddress = process.env.OPENSHIFT_NODEJS_IP;
        self.port      = process.env.OPENSHIFT_NODEJS_PORT || 8080;

        if (typeof self.ipaddress === "undefined") {
            //  Log errors on OpenShift but continue w/ 127.0.0.1 - this
            //  allows us to run/test the app locally.
            console.warn('No OPENSHIFT_NODEJS_IP var, using 127.0.0.1');
            self.ipaddress = "127.0.0.1";
            
        if(process.env.OPENSHIFT_MONGODB_DB_PASSWORD){
            connection_string = process.env.OPENSHIFT_MONGODB_DB_USERNAME + ":" +
                process.env.OPENSHIFT_MONGODB_DB_PASSWORD + "@" +
                process.env.OPENSHIFT_MONGODB_DB_HOST + ':' +
                process.env.OPENSHIFT_MONGODB_DB_PORT + '/' +
                process.env.OPENSHIFT_APP_NAME
            
            db = mongojs.connect(connection_string,['wagers']);
        }
        };
    };


    /**
     *  Populate the cache.
     */
    self.populateCache = function() {
        if (typeof self.zcache === "undefined") {
            self.zcache = { 'index.html': '' };
        }

        //  Local cache for static content.
        self.zcache['index.html'] = fs.readFileSync('./index.html');
    };


    /**
     *  Retrieve entry (content) from cache.
     *  @param {string} key  Key identifying content to retrieve from cache.
     */
    self.cache_get = function(key) { return self.zcache[key]; };


    /**
     *  terminator === the termination handler
     *  Terminate server on receipt of the specified signal.
     *  @param {string} sig  Signal to terminate on.
     */
    self.terminator = function(sig){
        if (typeof sig === "string") {
           console.log('%s: Received %s - terminating sample app ...',
                       Date(Date.now()), sig);
           process.exit(1);
        }
        console.log('%s: Node server stopped.', Date(Date.now()) );
    };


    /**
     *  Setup termination handlers (for exit and a list of signals).
     */
    self.setupTerminationHandlers = function(){
        //  Process on exit and signals.
        process.on('exit', function() { self.terminator(); });

        // Removed 'SIGPIPE' from the list - bugz 852598.
        ['SIGHUP', 'SIGINT', 'SIGQUIT', 'SIGILL', 'SIGTRAP', 'SIGABRT',
         'SIGBUS', 'SIGFPE', 'SIGUSR1', 'SIGSEGV', 'SIGUSR2', 'SIGTERM'
        ].forEach(function(element, index, array) {
            process.on(element, function() { self.terminator(element); });
        });
    };


    /*  ================================================================  */
    /*  App server functions (main app logic here).                       */
    /*  ================================================================  */

    /**
     *  Create the routing table entries + handlers for the application.
     */
    self.createRoutes = function() {
        self.routes = { };

        self.routes['/'] = function(req, res){
    console.log("GET the homepage");
    res
        .status(200)
        .sendFile(path.join(__dirname, 'public','index.html'));
}); 
        
        self.routes['/asciimo'] = function(req, res) {
            var link = "http://i.imgur.com/kmbjB.png";
            res.send("<html><body><img src='" + link + "'></body></html>");
        };
        

        //.get all wagers
        self.routes['allWagers'] = function(req, res) {
            //        Bear.find(function(err, bears) {
            //            if (err)
            //                res.send(err);
            //
                        res.json(wagers);
            //        });            
        };
        
        //.get a wager
        self.routes['aWager'] = function(req, res) {
            db.wagers.find({email: req.params.email}, function(err, wagers){
                if(err)console.log("error");
                else wagers.forEach(function(returnedWager){
                    res.json(returnedWager);
                })
            });
        };
        
        //.delete A Wager
        self.routes['deleteWager'] = function(req, res) {
            //        Bear.remove({
            //            _id: req.params.bear_id
            //        }, function(err, bear) {
            //            if (err)
            //                res.send(err);
            //
            //            res.json({ message: 'Successfully deleted' });
            //        });
        };
        
        //.post A Wager
        self.routes['createWager'] = function(req, res) {
            db.wagers.save({
              email: req.params.email,
              amount: req.params.amount,
              amountBTC: req.params.amountBTC,
              proposition: req.params.proposition,
              duration: req.params.duration,
              startMetric: req.params.startMetric,
              endMetric: req.params.endMetric,
              publicAddress: req.params.publicAddress
            }, function(err, saved){
                if(err)console.log("error");
                else console.log("saved");
            });
            
        };
    };

    /**
     *  Setting up the router.
     */
    self.configureRouter = function(){
           
        self.app.use(express.static(path.join(__dirname, 'public')));
        self.app.get('/wagers', self.routes['allWagers']);
        self.app.get('/wagers/wager/:email', self.routes['aWager']);
        self.app.delete('/wagers/wager/:email', self.routes['deleteWager']);
        self.app.post('/wagers/wager/:email/:amount/:amountBTC/:proposition/:duration/:startMetric/:endMetric/:publicAddress', self.routes['createWager']);
        
        // middleware to use for all requests
        self.app.use(function(req, res, next) {
            // do logging
            res.header("Access-Control-Allow-Origin", "*");
            res.header("Access-Control-Allow-Headers", "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");
            res.header("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");

            console.log('Something is happening.');
            next(); // make sure we go to the next routes and don't stop here
        });
    };

    /**
     *  Initialize the server (express) and create the routes and register
     *  the handlers.
     */
    self.initializeServer = function() {
        self.createRoutes();
        self.app = express.createServer();

        //  Add handlers for the app (from the routes).
        for (var r in self.routes) {
            self.app.get(r, self.routes[r]);
        }
        
        //Set up the router
        self.configureRouter();
    };


    /**
     *  Initializes the sample application.
     */
    self.initialize = function() {
        self.setupVariables();
        self.populateCache();
        self.setupTerminationHandlers();

        // Create the express server and routes.
        self.initializeServer();
    };


    /**
     *  Start the server (starts up the sample application).
     */
    self.start = function() {
        //  Start the app on the specific interface (and port).
        self.app.listen(self.port, self.ipaddress, function() {
            console.log('%s: Node server started on %s:%d ...',
                        Date(Date.now() ), self.ipaddress, self.port);
        });
    };

};   /*  Sample Application.  */



/**
 *  main():  Main code.
 */
var zapp = new SampleApp();
zapp.initialize();
zapp.start();

